# Generated by Django 5.1.3 on 2024-11-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urazy', '0002_pohlavi_rok_vek_rok_alter_vek_vek'),
    ]

    operations = [
        migrations.AddField(
            model_name='pohlavi',
            name='pocet',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vek',
            name='pocet',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
