# Generated by Django 5.1.3 on 2024-11-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urazy', '0003_pohlavi_pocet_vek_pocet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zpusob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zpusob', models.CharField(max_length=7)),
                ('rok', models.IntegerField(blank=True, default=None, null=True)),
                ('pocet', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
