# Generated by Django 5.1.3 on 2025-01-04 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urazy', '0004_zpusob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zpusob_popis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zpusob', models.CharField(max_length=10, unique=True)),
                ('popis', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='zpusob',
            name='zpusob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zpusoby', to='urazy.zpusob_popis'),
        ),
    ]
