# Generated by Django 5.1.3 on 2025-01-04 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urazy', '0005_zpusob_popis_alter_zpusob_zpusob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zpusob_popis',
            name='zpusob',
        ),
        migrations.AddField(
            model_name='zpusob_popis',
            name='zpusob_popis',
            field=models.IntegerField(default=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zpusob',
            name='zpusob',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='urazy.zpusob_popis', to_field='zpusob_popis'),
        ),
        migrations.AlterField(
            model_name='zpusob_popis',
            name='popis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
