# Generated by Django 5.1.3 on 2025-01-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urazy', '0006_remove_zpusob_popis_zpusob_zpusob_popis_zpusob_popis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpusob',
            name='zpusob',
            field=models.IntegerField(choices=[(1, 'Chodec zraněný při dopravní nehodě'), (2, 'Cyklista zraněný při dopravní nehodě'), (3, 'Jezdec na motocyklu zraněný při dopravní nehodě'), (4, 'Člen osádky tříkolového motorového vozidla zraněný při dopravní nehodě'), (5, 'Člen osádky osobního automobilu zraněný při dopravní nehodě'), (6, 'Člen osádky dodávkového nebo lehkého nákladního automobilu zraněný při dopravní nehodě'), (7, 'Člen osádky těžkého nákladního vozidla zraněný při dopravní nehodě'), (8, 'Člen osádky autobusu zraněný při dopravní nehodě'), (9, 'Jiné nehody při pozemní dopravě'), (10, 'Nehody při vodní dopravě'), (11, 'Nehody při dopravě vzduchem a vesmírným prostorem'), (12, 'Jiné a neurčené dopravní nehody'), (13, 'Pády'), (14, 'Vystavení neživotním mechanickým silám'), (15, 'Vystavení životním mechanickým silám'), (16, 'Náhodné (u)tonutí a potopení'), (17, 'Jiná náhodná ohrožení dýchání'), (18, 'Vystavení elektrickému proudu, ozáření a extrémní okolní teplotě a tlaku vzduchu'), (19, 'Vystavení kouři, ohni, dýmu a plamenů'), (20, 'Kontakt s horkem a horkými látkami'), (21, 'Kontakt s jedovatými živočichy a rostlinam'), (22, 'Vystavení přírodním silám'), (23, 'Neúmyslné sebezranění'), (24, 'Úmyslné sebezranění'), (25, 'Úmyslná sebevražda')]),
        ),
        migrations.DeleteModel(
            name='Zpusob_popis',
        ),
    ]
