# Generated by Django 5.1.3 on 2025-01-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urazy', '0007_alter_zpusob_zpusob_delete_zpusob_popis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpusob',
            name='zpusob',
            field=models.IntegerField(choices=[('V01_V09', 'Chodec zraněný při dopravní nehodě'), ('V10_V19', 'Cyklista zraněný při dopravní nehodě'), ('V20_V29', 'Jezdec na motocyklu zraněný při dopravní nehodě'), ('V30_V39', 'Člen osádky tříkolového motorového vozidla zraněný při dopravní nehodě'), ('V40_V49', 'Člen osádky osobního automobilu zraněný při dopravní nehodě'), ('V50_V59', 'Člen osádky dodávkového nebo lehkého nákladního automobilu zraněný při dopravní nehodě'), ('V60_V69', 'Člen osádky těžkého nákladního vozidla zraněný při dopravní nehodě'), ('V70_V79', 'Člen osádky autobusu zraněný při dopravní nehodě'), ('V80_V89', 'Jiné nehody při pozemní dopravě'), ('V90_V94', 'Nehody při vodní dopravě'), ('V95_V97', 'Nehody při dopravě vzduchem a vesmírným prostorem'), ('V98_V99', 'Jiné a neurčené dopravní nehody'), ('W00_W19', 'Pády'), ('W20_W49', 'Vystavení neživotným mechanickým silám'), ('W50_W64', 'Vystavení životným mechanickým silám'), ('W65_W74', 'Náhodné (u)tonutí a potopení'), ('W75_W84', 'Jiná náhodná ohrožení dýchání'), ('W85_W99', 'Vystavení elektrickému proudu, ozáření a extrémní okolní teplotě a tlaku vzduchu'), ('X00_X09', 'Vystavení kouři, ohni, dýmu a plamenů'), ('X10_X19', 'Kontakt s horkem a horkými látkami'), ('X20_X29', 'Kontakt s jedovatými živočichy a rostlinam'), ('X30_X39', 'Vystavení přírodním silám'), ('X40_X49', 'Neúmyslné sebezranění'), ('X50_X57', 'Úmyslné sebezranění'), ('X58_X59', 'Úmyslná sebevražda')]),
        ),
    ]
